from __future__ import annotations
from typing import Any, Dict, List, Set

# ======== Classes ========


class SlaterDeterminant:
    def __init__(self, N: int, coef: complex, orbitals: List[int]) -> None: ...
    def __reduce__(self) -> Any: ...
    def __str__(self) -> str: ...
    def adjoint(self) -> SlaterDeterminant: ...
    @property
    def N(self) -> int: ...
    @property
    def coef(self) -> complex: ...
    @property
    def orbitals(self) -> List[int]: ...
    @property
    def encoding(self) -> int: ...
    def __add__(self, right: SlaterDeterminant) -> Wavefunction: ...
    def __rmul__(self, left: complex) -> SlaterDeterminant: ...


class Wavefunction:
    def __init__(self, N: int, cutoff: float = 1e-8) -> None: ...
    def __str__(self) -> str: ...
    def norm(self) -> float: ...
    def append_slater_determinant(self, sdet: SlaterDeterminant) -> None: ...
    def adjoint(self) -> Wavefunction: ...
    def remove_global_phase(self) -> None: ...
    def remove_near_zero_terms(self, cutoff: float) -> None: ...
    @property
    def s(self) -> Any: ...
    @property
    def N(self) -> int: ...
    # algebra
    def __mul__(self, right: Wavefunction) -> complex: ...
    def __rmul__(self, left: complex) -> Wavefunction: ...
    def __add__(self, right: SlaterDeterminant) -> Wavefunction: ...


class PauliString:
    def __init__(self, N: int, coef: complex, paulis: List[int]) -> None: ...
    def __str__(self) -> str: ...
    def adjoint(self) -> PauliString: ...
    @property
    def N(self) -> int: ...
    @property
    def coef(self) -> complex: ...
    @property
    def string(self) -> str: ...
    @property
    def matrix(self) -> Any: ...
    # algebra
    def __mul__(self, right: Wavefunction |
                PauliString) -> Wavefunction | PauliString: ...

    def __rmul__(self, left: complex) -> PauliString: ...
    def __add__(self, right: PauliString) -> PauliSum: ...


class PauliSum:
    def __init__(self, N: int, cutoff: float = 1e-12) -> None: ...
    def __str__(self) -> str: ...
    def append_pauli_string(self, pString: PauliString) -> None: ...
    def adjoint(self) -> PauliSum: ...
    def get_pauli_strings(self) -> List[PauliString]: ...
    @property
    def p(self) -> Any: ...
    @property
    def N(self) -> int: ...
    @property
    def matrix(self) -> Any: ...
    # algebra
    def __mul__(self, right: Wavefunction | PauliSum |
                DensityMatrix) -> Wavefunction | PauliSum | DensityMatrix: ...

    def __rmul__(self, left: complex) -> PauliSum: ...
    def __add__(self, right: PauliSum) -> PauliSum: ...


class OuterProduct:
    def __init__(self, N: int, coef: complex,
                 ket_orbitals: List[int], bra_orbitals: List[int]) -> None: ...

    def __str__(self) -> str: ...
    @property
    def N(self) -> int: ...
    @property
    def coef(self) -> complex: ...
    @property
    def ket_orbitals(self) -> List[int]: ...
    @property
    def bra_orbitals(self) -> List[int]: ...
    @property
    def encoding(self) -> int: ...
    # algebra
    def __add__(self, right: OuterProduct) -> DensityMatrix: ...
    def __rmul__(self, left: complex) -> OuterProduct: ...
    def __mul__(self, right: PauliString) -> OuterProduct: ...


class DensityMatrix:
    def __init__(self, N: int, cutoff: float = 1e-16) -> None: ...
    def __str__(self) -> str: ...
    def trace(self) -> complex: ...
    def append_outer_product(self, oprod: OuterProduct) -> None: ...
    def remove_global_phase(self) -> None: ...
    def remove_near_zero_terms(self, cutoff: float) -> None: ...
    @property
    def o(self) -> Any: ...
    @property
    def N(self) -> int: ...
    # algebra
    def __mul__(self, right: DensityMatrix | PauliString |
                PauliSum) -> DensityMatrix: ...

    def __rmul__(self, left: complex) -> DensityMatrix: ...
    def __add__(self, right: OuterProduct) -> None: ...

# ======== Module-level operations ========


def slater_determinant_scalar_multiplication(
    sdet: SlaterDeterminant, scalar: complex) -> SlaterDeterminant: ...


def wavefunction_scalar_multiplication(
    wfn: Wavefunction, scalar: complex) -> Wavefunction: ...


def wavefunction_multiplication(
    bra: Wavefunction, ket: Wavefunction) -> complex: ...


def wavefunction_pauli_string_multiplication(
    pString: PauliString, wfn: Wavefunction) -> Wavefunction: ...


def wavefunction_pauli_sum_multiplication(
    pSum: PauliSum, wfn: Wavefunction) -> Wavefunction: ...


def wavefunction_pauli_string_evolution(
    pString: PauliString, wfn: Wavefunction, epsilon: complex) -> Wavefunction: ...


def wavefunction_pauli_sum_evolution(
    pSum: PauliSum, wfn: Wavefunction, epsilon: complex) -> Wavefunction: ...


def pauli_string_scalar_multiplication(
    pString: PauliString, scalar: complex) -> PauliString: ...


def pauli_string_multiplication(
    left: PauliString, right: PauliString) -> PauliString: ...


def pauli_sum_scalar_multiplication(
    pSum: PauliSum, scalar: complex) -> PauliSum: ...


def pauli_sum_multiplication(left: PauliSum, right: PauliSum) -> PauliSum: ...


def pauli_sum_collect_measurements(pSum: PauliSum) -> Set[str]: ...


def pauli_sum_evaluate_expectation(
    pSum: PauliSum, tomography: dict) -> complex: ...


def pauli_sum_addition(left: PauliSum, right: PauliSum) -> PauliSum: ...


def wavefunction_perform_tomography(
    wfn: Wavefunction, measurements: Set[str]) -> dict: ...


def wavefunction_to_probability_distribution(
    wfn: Wavefunction) -> Dict[str, float]: ...


def outer_product_scalar_multiplication(
    oprod: OuterProduct, scalar: complex) -> OuterProduct: ...


def outer_product_pauli_string_left_multiplication(
    pString: PauliString, oprod: OuterProduct) -> OuterProduct: ...


def outer_product_pauli_string_right_multiplication(
    oprod: OuterProduct, pString: PauliString) -> OuterProduct: ...


def density_matrix_from_wavefunction(
    wfn: Wavefunction) -> DensityMatrix: ...


def density_matrix_scalar_multiplication(
    dm: DensityMatrix, scalar: complex) -> DensityMatrix: ...


def density_matrix_multiplication(
    left: DensityMatrix, right: DensityMatrix) -> DensityMatrix: ...


def density_matrix_pauli_string_left_multiplication(
    pString: PauliString, dm: DensityMatrix) -> DensityMatrix: ...


def density_matrix_pauli_string_right_multiplication(
    dm: DensityMatrix, pString: PauliString) -> DensityMatrix: ...


def density_matrix_pauli_sum_left_multiplication(
    pSum: PauliSum, dm: DensityMatrix) -> DensityMatrix: ...


def density_matrix_pauli_sum_right_multiplication(
    dm: DensityMatrix, pSum: PauliSum) -> DensityMatrix: ...


def density_matrix_pauli_string_evolution(
    pString: PauliString, dm: DensityMatrix, epsilon: complex) -> DensityMatrix: ...


def density_matrix_pauli_sum_evolution(
    pSum: PauliSum, dm: DensityMatrix, epsilon: complex) -> DensityMatrix: ...


def density_matrix_CPTP_evolution(
    H: PauliSum, Ls: List[PauliSum], dm: DensityMatrix, t: float) -> DensityMatrix: ...


def density_matrix_perform_tomography(
    dm: DensityMatrix, measurements: Set[str]) -> dict: ...


def density_matrix_to_probability_distribution(
    dm: DensityMatrix) -> Dict[str, float]: ...
