from __future__ import annotations
from typing import TYPE_CHECKING, Any, Dict, List, Set

if TYPE_CHECKING:
    from .pauli import PauliString, PauliSum
    from .wavefunction import Wavefunction


class OuterProduct:
    def __init__(self, N: int, coef: complex,
                 ket_orbitals: List[int], bra_orbitals: List[int]) -> None: ...

    def __str__(self) -> str: ...
    @property
    def N(self) -> int: ...
    @property
    def coef(self) -> complex: ...
    @property
    def ket_orbitals(self) -> List[int]: ...
    @property
    def bra_orbitals(self) -> List[int]: ...
    @property
    def encoding(self) -> int: ...
    # algebra
    def __add__(self, right: OuterProduct) -> DensityMatrix: ...
    def __rmul__(self, left: complex) -> OuterProduct: ...
    def __mul__(self, right: PauliString) -> OuterProduct: ...


class DensityMatrix:
    def __init__(self, N: int, cutoff: float = 1e-16) -> None: ...
    def __str__(self) -> str: ...
    def trace(self) -> complex: ...
    def append_outer_product(self, oprod: OuterProduct) -> DensityMatrix: ...
    def remove_global_phase(self) -> DensityMatrix: ...
    def remove_near_zero_terms(self, cutoff: float) -> DensityMatrix: ...
    @property
    def o(self) -> Any: ...
    @property
    def N(self) -> int: ...
    # algebra

    def __mul__(self, right: DensityMatrix | PauliString |
                PauliSum) -> DensityMatrix: ...

    def __rmul__(self, left: complex | PauliString |
                 PauliSum) -> DensityMatrix: ...

    def __add__(self, right: OuterProduct) -> DensityMatrix: ...


def outer_product_scalar_multiplication(
    oprod: OuterProduct, scalar: complex) -> OuterProduct: ...


def outer_product_pauli_string_left_multiplication(
    pString: PauliString, oprod: OuterProduct) -> OuterProduct: ...


def outer_product_pauli_string_right_multiplication(
    oprod: OuterProduct, pString: PauliString) -> OuterProduct: ...


def density_matrix_from_wavefunction(
    wfn: Wavefunction) -> DensityMatrix: ...


def density_matrix_scalar_multiplication(
    dm: DensityMatrix, scalar: complex) -> DensityMatrix: ...


def density_matrix_multiplication(
    left: DensityMatrix, right: DensityMatrix) -> DensityMatrix: ...


def density_matrix_pauli_string_left_multiplication(
    pString: PauliString, dm: DensityMatrix) -> DensityMatrix: ...


def density_matrix_pauli_string_right_multiplication(
    dm: DensityMatrix, pString: PauliString) -> DensityMatrix: ...


def density_matrix_pauli_sum_left_multiplication(
    pSum: PauliSum, dm: DensityMatrix) -> DensityMatrix: ...


def density_matrix_pauli_sum_right_multiplication(
    dm: DensityMatrix, pSum: PauliSum) -> DensityMatrix: ...


def density_matrix_pauli_string_evolution(
    pString: PauliString, dm: DensityMatrix, epsilon: complex) -> DensityMatrix: ...


def density_matrix_pauli_sum_evolution(
    pSum: PauliSum, dm: DensityMatrix, epsilon: complex) -> DensityMatrix: ...


def density_matrix_CPTP_evolution(
    H: PauliSum, Ls: List[PauliSum], dm: DensityMatrix, t: complex) -> DensityMatrix: ...


def density_matrix_perform_tomography(
    dm: DensityMatrix, measurements: Set[str]) -> dict: ...


def density_matrix_to_probability_distribution(
    dm: DensityMatrix) -> Dict[str, float]: ...
