from __future__ import annotations
from typing import TYPE_CHECKING, Any, Dict, List, Set

if TYPE_CHECKING:
    from .density_matrix import DensityMatrix


class PauliString:
    def __init__(self, N: int, coef: complex, paulis: List[str]) -> None: ...
    def __str__(self) -> str: ...
    def adjoint(self) -> PauliString: ...
    @property
    def N(self) -> int: ...
    @property
    def coef(self) -> complex: ...
    @property
    def string(self) -> str: ...
    @property
    def matrix(self) -> Any: ...
    # algebra
    def __mul__(self, right:
                PauliString) -> PauliString: ...

    def __rmul__(self, left: complex) -> PauliString: ...
    def __add__(self, right: PauliString) -> PauliSum: ...


class PauliSum:
    def __init__(self, N: int, cutoff: float = 1e-12) -> None: ...
    def __str__(self) -> str: ...
    def append_pauli_string(self, pString: PauliString) -> PauliSum: ...
    def adjoint(self) -> PauliSum: ...
    def get_pauli_strings(self) -> List[PauliString]: ...
    @property
    def p(self) -> Any: ...
    @property
    def N(self) -> int: ...
    @property
    def matrix(self) -> Any: ...
    # algebra
    def __mul__(self, right:  PauliSum |
                DensityMatrix) -> PauliSum | DensityMatrix: ...

    def __rmul__(self, left: complex) -> PauliSum: ...
    def __add__(self, right: PauliSum) -> PauliSum: ...


def pauli_string_scalar_multiplication(
    pString: PauliString, scalar: complex) -> PauliString: ...


def pauli_string_multiplication(
    left: PauliString, right: PauliString) -> PauliString: ...


def pauli_sum_scalar_multiplication(
    pSum: PauliSum, scalar: complex) -> PauliSum: ...


def pauli_sum_multiplication(left: PauliSum, right: PauliSum) -> PauliSum: ...


def pauli_sum_collect_measurements(pSum: PauliSum) -> Set[str]: ...


def pauli_sum_evaluate_expectation(
    pSum: PauliSum, tomography: dict) -> complex: ...


def pauli_sum_addition(left: PauliSum, right: PauliSum) -> PauliSum: ...
